use anchor_lang::prelude::*;
use anchor_lang::solana_program::{hash::hash,instruction::{AccountMeta,Instruction},program::{get_return_data,invoke},pubkey};
declare_id!("CuNH1eDimEDxxgomwG7VzYd9RDdiKPVkTBjXWeg9jkVF");
const DEVNET_TXLINE_PROGRAM:Pubkey=pubkey!("6pW64gN1s2uqjHkn1unFeEjAwJkPGHoppGvS715wyP2J");
const MAINNET_TXLINE_PROGRAM:Pubkey=pubkey!("9ExbZjAapQww1vfcisDmrngPinHTEfpjYRWMunJgcKaA");
#[program]
pub mod match_dna{use super::*;pub fn initialize_witness(ctx:Context<InitializeWitness>,fixture_hash:[u8;32],commitment:[u8;32],kickoff_at:i64)->Result<()>{let c=Clock::get()?;let w=&mut ctx.accounts.witness;w.owner=ctx.accounts.owner.key();w.fixture_hash=fixture_hash;w.commitment=commitment;w.committed_slot=c.slot;w.committed_at=c.unix_timestamp;w.kickoff_at=kickoff_at;w.revealed=false;w.reveal_hash=[0;32];w.bump=ctx.bumps.witness;Ok(())}pub fn reveal_witness(ctx:Context<RevealWitness>,preimage:Vec<u8>)->Result<()>{require!(preimage.len()<=1024,ErrorCode::PreimageTooLarge);let w=&mut ctx.accounts.witness;require!(!w.revealed,ErrorCode::AlreadyRevealed);let value=hash(&preimage).to_bytes();require!(value==w.commitment,ErrorCode::CommitmentMismatch);w.revealed=true;w.reveal_hash=value;Ok(())}pub fn verify_txline_and_seal(ctx:Context<Seal>,instruction_data:Vec<u8>,timeline_hash:[u8;32],proof_bundle_hash:[u8;32],final_state_hash:[u8;32],audio_hash:[u8;32],media_hash:[u8;32])->Result<()>{require!(instruction_data.len()<=8192,ErrorCode::CpiDataTooLarge);require!(ctx.accounts.witness.revealed,ErrorCode::WitnessNotRevealed);let program=ctx.accounts.txline_program.key();require!(program==DEVNET_TXLINE_PROGRAM||program==MAINNET_TXLINE_PROGRAM,ErrorCode::UnsupportedTxlineProgram);require_keys_eq!(*ctx.accounts.txline_root.owner,program,ErrorCode::InvalidRootOwner);invoke(&Instruction{program_id:program,accounts:vec![AccountMeta::new_readonly(ctx.accounts.txline_root.key(),false)],data:instruction_data},&[ctx.accounts.txline_root.to_account_info(),ctx.accounts.txline_program.to_account_info()])?;let(return_program,data)=get_return_data().ok_or(ErrorCode::MissingReturnData)?;require_keys_eq!(return_program,program,ErrorCode::InvalidReturnProgram);require!(data.as_slice()==[1u8],ErrorCode::PredicateRejected);let g=&mut ctx.accounts.genome;require!(!g.sealed,ErrorCode::AlreadySealed);g.witness=ctx.accounts.witness.key();g.owner=ctx.accounts.owner.key();g.timeline_hash=timeline_hash;g.proof_bundle_hash=proof_bundle_hash;g.final_state_hash=final_state_hash;g.audio_hash=audio_hash;g.media_hash=media_hash;g.txline_program=program;g.txline_root=ctx.accounts.txline_root.key();g.sealed_at=Clock::get()?.unix_timestamp;g.sealed=true;g.bump=ctx.bumps.genome;Ok(())}}
#[derive(Accounts)]#[instruction(fixture_hash:[u8;32])]pub struct InitializeWitness<'info>{#[account(mut)]pub owner:Signer<'info>,#[account(init,payer=owner,space=WitnessCommit::SPACE,seeds=[b"witness",owner.key().as_ref(),fixture_hash.as_ref()],bump)]pub witness:Account<'info,WitnessCommit>,pub system_program:Program<'info,System>}
#[derive(Accounts)]pub struct RevealWitness<'info>{pub owner:Signer<'info>,#[account(mut,has_one=owner,seeds=[b"witness",owner.key().as_ref(),witness.fixture_hash.as_ref()],bump=witness.bump)]pub witness:Account<'info,WitnessCommit>}
#[derive(Accounts)]pub struct Seal<'info>{#[account(mut)]pub owner:Signer<'info>,#[account(has_one=owner,seeds=[b"witness",owner.key().as_ref(),witness.fixture_hash.as_ref()],bump=witness.bump)]pub witness:Account<'info,WitnessCommit>,#[account(init_if_needed,payer=owner,space=MatchGenome::SPACE,seeds=[b"genome",witness.key().as_ref()],bump)]pub genome:Account<'info,MatchGenome>,/// CHECK: allowlisted and executable
#[account(executable)]pub txline_program:UncheckedAccount<'info>,/// CHECK: ownership verified in handler
pub txline_root:UncheckedAccount<'info>,pub system_program:Program<'info,System>}
#[account]pub struct WitnessCommit{pub owner:Pubkey,pub fixture_hash:[u8;32],pub commitment:[u8;32],pub committed_slot:u64,pub committed_at:i64,pub kickoff_at:i64,pub revealed:bool,pub reveal_hash:[u8;32],pub bump:u8}impl WitnessCommit{pub const SPACE:usize=8+32+32+32+8+8+8+1+32+1;}
#[account]pub struct MatchGenome{pub witness:Pubkey,pub owner:Pubkey,pub timeline_hash:[u8;32],pub proof_bundle_hash:[u8;32],pub final_state_hash:[u8;32],pub audio_hash:[u8;32],pub media_hash:[u8;32],pub txline_program:Pubkey,pub txline_root:Pubkey,pub sealed_at:i64,pub sealed:bool,pub bump:u8}impl MatchGenome{pub const SPACE:usize=8+32*9+8+1+1;}
#[error_code]pub enum ErrorCode{#[msg("Preimage too large")]PreimageTooLarge,#[msg("Already revealed")]AlreadyRevealed,#[msg("Commitment mismatch")]CommitmentMismatch,#[msg("Witness not revealed")]WitnessNotRevealed,#[msg("CPI data too large")]CpiDataTooLarge,#[msg("Unsupported TxLINE program")]UnsupportedTxlineProgram,#[msg("Invalid root owner")]InvalidRootOwner,#[msg("Missing return data")]MissingReturnData,#[msg("Invalid return program")]InvalidReturnProgram,#[msg("TxLINE predicate rejected")]PredicateRejected,#[msg("Genome already sealed")]AlreadySealed}
